qase-tms/qase-javascript

- qase-jest/src/index.ts
This behaviour is described in documentation, but was actually missing.
> jest: fix disabling reporting when `QASE_REPORT` is not set

- qase-jest/README.md
- qase-jest/examples/jest.config.js
- qase-jest/package.json
- qase-jest/src/index.ts
- massive rewrite to avoid async bugs (closes #17)
- make all options passed as env variables take precedence over options from config
- add new option `environmentId` (and corresponding env variable `QASE_ENVIRONMENT_ID`) to specify run environment (closes #42)
- minor tweaks to docs and examples
> `jest-qase-reporter` v1.2.0

- qaseio/src/models/runs.ts
- qaseio/test/services/runs.test.ts
Link to. API: https://developers.qase.io/reference/create-run
When we try to create a Test Run with qase-jest-reporter, the new Test Run has no is_autotest field.
So when we try to filter all test runs by the Automation filter, we see an empty page instead of the Test Run we just created.
> Updated the RunCreate class with is_autotest field

- qase-playwright/package-lock.json
- qase-playwright/package.json
- qase-playwright/tsconfig.json
Problem: compiler puts js files to /dist/src instead of /dist
Solution: ignore unnecessary ts files when building
> [qase-playwright] ignore unnecessary ts files when build

- qase-cypress/package-lock.json
- qase-cypress/package.json
- qase-cypress/src/index.ts
Related: #74 
`deasync` (https://github.com/abbr/deasync) is a native dependency, which can cause problems on many platforms.
Would it be possible to remove it?
- https://github.com/cypress-io/cypress-parcel-preprocessor/issues/39
- https://github.com/abbr/deasync/issues/142
use Atomics.wait (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait)
> [qase-cypress] Feature request: Removing dependency on deasync

- qase-cypress/src/index.ts
Fast and dirty solving the problem with reporting many test results
Next step will be using bulk reporting method
> increase cypress reporter timeout

- qaseio/package-lock.json
- qaseio/package.json
- qaseio/src/qaseio.ts
Problem: for attachments uploading, we need to use in api FormData library, but it is not imported in autogenerated clients
Solution: inject FormData via ApiClient constructor
> added form-data constructor to api init params

- qase-playwright/src/index.ts
Added the missed property `environment_id` to the create run method of the qase-playwright reporter.
> added the missed `environment_id`

- qase-cypress/src/index.ts
- qase-cypress/test/plugin.test.ts
Adding support for `auto create defects` when a test fails by setting defect to true in Qase test results. 
**What changed:**
- Added a defect field to `caseResultBulkObject` objects  and set to true only if the test result is `failed`.
- Added unit test to verify that all `resultsForPublishing` has a defect field and the value is set appropriately based on the test status.
**How to test**:  
1. Run cypress tests as normal 
> feat:cypress auto create defect

- qase-playwright/src/index.ts
- qase-playwright/test/plugin.test.ts
Added a defect field to `caseObject` objects and set to true only if the test result is failed.
Added unit test to verify that all resultsForPublishing has a defect field and the value is set appropriately based on the test status.
1. Run playwright tests as normal
> feat:playwright auto create defect

- qase-cucumberjs/src/index.ts
- qase-cucumberjs/test/plugin.test.ts
Added a defect field to `ResultCreate` objects and set to true only if the test result is failed.
Added unit test to verify that all results has a defect field and the value is set appropriately based on the test status. (both known and unknown cases)
1. Run cucumberjs tests as normal
> feat: [qase-cucumberjs] added support for create auto defect and unit tests

- qase-newman/src/index.ts
- qase-newman/test/plugin.test.ts
- Added a defect field to `BulkCaseObject` objects and set to true only if the test result is failed.
- Added unit test to verify that all results has a defect field and the value is set appropriately based on the test status. (both known and unknown cases)
**How to test**: 
1. Run newman tests as normal
> feat: [qase-newman] add support for auto create defect and unit tests

- qase-jest/src/index.ts
- qase-jest/test/plugin.test.ts
- Added a defect field to `caseObject` objects and set to true only if the test result is failed.
- Added unit test to verify that all results have a defect field and the value is set appropriately based on the test status. (both known and unknown cases)
1. Run jest tests as normal
> feat: [qase-jest] add support for auto create defect and unit tests

- qase-testcafe/examples/package.json
- qase-testcafe/src/index.ts
- qase-testcafe/test/plugin.test.ts
- Added a defect field to `caseObject` objects and set to true only if the test result is failed.
- Added unit test to verify that all results has a defect field and the value is set appropriately based on the test status. (both known and unknown cases)
- Updated examples test command since full-page screenshots aren't supported in chrome, this was causing an error when QASE would try to find a screenshot after failure to upload, but it didn't exist.
1. Run testcafe tests as normal
> feat: [qase-testcafe] add support for auto create defect and unit tests

- qase-cucumberjs/examples/.qaserc
- qase-cucumberjs/src/index.ts
- qase-cucumberjs/test/plugin.test.ts
runComplete [true/false] - Permission for automatic completion of the test run
- Updated config.runComplete to be false by default
- Check for `config.runComplete` = true in `publishResults` and make API call to automatically complete run
- included unit tests for checking different states of config.runComplete based on environmental variable and reporter options
- Updated examples to include runComeplete as a reporter option in `.qaserc`
- Run cucumberjs tests as normal
- Observe that the run is automatically completed based on the new updates.
resolve #247
> feat(#247) : qase cucumberjs runComplete option 

- qase-newman/examples/package.json
- qase-newman/src/index.ts
- qase-newman/src/reportBulk.js
- qase-newman/test/plugin.test.ts
runComplete [true/false] - Permission for automatic completion of the test run
**What changed:**
- Updated `options.runComplete` to be false by default
- Added `runComplete` to `reporting_config` for reportBulk usage
- Check for runComplete = true in reportBulk.js and make API call to automatically complete run
- included unit tests for checking different states of options.runComplete based on environmental variable and reporter options
- Updated examples to include runComeplete as a reporter option in the `test` command
**How to test**?:
- Run newman tests as normal
- Observe that the run is automatically completed based on the new updates. 
resolve #247
> feat(#247): [qase-newman] added runComplete option support

- qase-newman/src/index.ts
- qase-newman/test/plugin.test.ts
Link test run to a specific environment by specifying **QASE_ENVIRONMENT_ID**, or using **environmentalId** reporter option. 
- Update config to set environmentId by environmental variable or report options
- Set environmentId to undefined by default since this is optional
- Added unit tests to account for all states when setting the environment ID
1. Ensure that you have an environment configured in your QASE account
2. Run newman tests and specify the environment  ID 
```
QASE_ENVIRONMENT_ID=your_environment_id npm run tests
or 
newman run ./sample-collection.json -r qase --reporter-qase-logging --reporter-qase-projectCode project_code --reporter-qase-apiToken api_key --reporter-qase-rootSuiteTitle 'Newman tests' --reporter-qase-environmentId …
```
> feat: [qase-newman] add support for optional environmentId

- qase-playwright/src/index.ts
Added additional log at the run completion so it'd be possible to open results right from the console output (especially useful for CI/CD runs).
Feature request: https://qase.canny.io/feature-requests/p/log-a-link-to-qase-test-run-in-playwright-test-runs
> feat: add run link

- .github/workflows/npm.yml
All three versions are outdated. First, let's get rid of the oldest ones.
Updating to v20 will be done in the next step.
* Give jobs more clear names
* Put job names first in the job definitions
* Rename matrix.prefix to matrix.package, which better reflects the
meaning of the variable.
* Rearrange matrix workflow items, so that thir list visually matches
the list of packages in this repo.
Update actions/checkout and actions/setup-node to the latest versions,
using Node.js v20.
This change removes the multiple warnings from the GitHub run view:
> The following actions uses node12 which is deprecated and will be forced
> to run on node16: actions/checkout@v2, actions/setup-node@v1. For more info:
> https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instea …
> Update CI workflows

- qaseio/src/generated/api/result-api.ts
qaseio: Unable to publish run results
--
Resolves the following error:
```
Error: Request failed with status code 404
at createError (/Users/gda/Documents/github/qase-javascript/node_modules/axios/lib/core/createError.js:16:15)
at settle (/Users/gda/Documents/github/qase-javascript/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/Users/gda/Documents/github/qase-javascript/node_modules/axios/lib/adapters/http.js:269:11)
at IncomingMessage.emit (node:events:531:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
> qaseio: Unable to publish run results

- .gitignore
- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-enum.ts
- qase-javascript-commons/src/env/env-to-config.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/options/options-type.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/writer/driver-enum.ts
- qase-javascript-commons/src/writer/fs-writer.ts
- qase-javascript-commons/src/writer/index.ts
qase-javascript-commons: add support for standard config
--
The following changes:
- renamed some ENV variables
- added chunk, fallback, plan and defect fields to the config
- renamed ext to format
- removed duplicates
> qase-javascript-commons: add support for standard config

- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/abstract-reporter.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/writer/driver-enum.ts
qase-javascript-commons: add fallback reporter
--
- Add suport the fallback reporter. If the upstream reporter throws any error then the listener will try to use the fallback reporter.
- Also fix the format enum.
---
qase-javascript-commons: add support for loading results in chunks
--
Add support for loading results in chunks to testops reporter. Default chunk size is 200.
---
qase-javascript-commons: update the error message format
--
First show the reason for the error. After show the stack trace
> qase-javascript-commons: add fallback reporter

- package-lock.json
- qase-cucumberjs/src/reporter.ts
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
- qase-javascript-commons/package.json
- qase-javascript-commons/src/formatter/index.ts
- qase-javascript-commons/src/formatter/jsonp-formatter.ts
- qase-javascript-commons/src/models/attachment.ts
- qase-javascript-commons/src/models/execution-sum.ts
- qase-javascript-commons/src/models/host-data.ts
- qase-javascript-commons/src/models/index.ts
- qase-javascript-commons/src/models/report.ts
- qase-javascript-commons/src/models/short-result.ts
- qase-javascript-commons/src/models/stats.ts
- qase-javascript-commons/src/models/step-data.ts
- qase-javascript-commons/src/models/step-execution.ts
- qase-javascript-commons/src/models/test-execution.ts
- qase-javascript-commons/src/models/test-result.ts
- qase-javascript-commons/src/models/test-step.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/writer/fs-writer.ts
- qase-javascript-commons/src/writer/writer-interface.ts
- qase-jest/src/reporter.ts
- qase-newman/src/reporter.ts
- qase-playwright/src/reporter.ts
- qase-testcafe/src/reporter.ts
qase-javascript-commons: refactor models
--
Add models which supports the v2 API. The following models:
- Report: stores shot information about run
- TestResultType: stores information about autotest
- TestStepType: stores information about steps
- TestExecution: stores information about test execution
- StepExecution: stores information about step execution
- Stats: stores information about statistics of test statuses
- ExecutionSum: stores information about statistics of test executions
---
qase-javascript-commons: refactor reporters
--
Support the new models in the reporters
---
qase-reporters: refactor listeners
--
Support the new models in the listeners
---
qase-javascript-commons: add support the jsonp format
--
Add support the jsonp format in the file reporter
--- …
> qase-javascript-commons: Add models which supports the v2 API

- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
qase-playwright: support new models
--
The following changes:
- support new models
- add a new way for set the test case metadata (ids, title, fields)
- add a method what adds attachments to a step or a test case
- support multiple ids. If add multiple ids to a test case, then count of results will be equal count of ids.
---
qase-javascript-commons: improve the file reporter
--
Add the following data to the report:
- environment
- run id
- start and end time
> qase-playwright: support new models

- qase-cucumberjs/src/reporter.ts
- qase-cypress/src/reporter.ts
- qase-javascript-commons/src/models/test-result.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/abstract-reporter.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-jest/src/reporter.ts
- qase-newman/src/reporter.ts
- qase-playwright/src/reporter.ts
- qase-testcafe/src/reporter.ts
qase-javascript-commons: add logic for supporting multiple IDs
--
Move this logic from the Playwright reporter to the abstract reporter
---
qase-reporters: support a new logic of commons
--
Support a new logic of the qase-javascript-commons package.
> qase-javascript-commons: add logic for supporting multiple IDs

- .github/workflows/npm.yml
- package-lock.json
Run CI precisely on packages saved in package-lock.json. All package updates will now be done and tested manually. Otherwise, we get updated versions of packages every time CI runs, and we're unable to say what's packaged in particular version.
This commit also updates package-lock.json.
See https://docs.npmjs.com/cli/v10/commands/npm-ci
> ci: use command `npm ci` to install packages in CI

- README.md
- examples/cucumberjs/package.json
- examples/cypress/package.json
- examples/jest/package.json
- examples/newman/package.json
- examples/playwright/package.json
- examples/testcafe/package.json
- package-lock.json
- package.json
- qase-cucumberjs/package.json
- qase-cypress/package.json
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-jest/package.json
- qase-newman/package.json
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-testcafe/package.json
- qaseio/changelog.md
- qaseio/package.json
* qaseio has changed API, and there is qaseio@2.0.4 already released, for v1 reporters, so it's heading towards a 2.1.0 release. It may change to 3.0.0 due to backwards-incompatible changes.
* Other packages didn't have a release in the 2.x.y series yet, so they are all now 2.0.0-beta.2 and heading towards 2.0.0.
* Examples have been updated to use 2.0.0-beta.2 reporters, but haven't been tested yet. It should be done is a separate task.
* Docs were not updated. They will follow the release.
Part of #536
Changelog drafts:
* https://github.com/qase-tms/qase-javascript/blob/release-beta-versions/qaseio/changelog.md
* https://github.com/qase-tms/qase-javascript/blob/release-beta-versions/qase-javascript-commons/changelog.md
* https://github.com/qase-tms/qase-javascript/blob/release-beta-versi …
> release: qaseio 2.1.0-beta.0, others 2.0.0-beta.2

- examples/playwright/package.json
- examples/playwright/test/arith.test.js
- qase-playwright/README.md
- qase-playwright/package.json
- qase-playwright/src/index.ts
Export the `qase` objet for simpler imports:
```js
import { qase } from 'playwright-qase-reporter';
```
instead of
```js
import { qase } from 'playwright-qase-reporter/playwright';
```
Resolve #538
> qase-playwright: import from package index, 2.0.0-beta.3

- examples/playwright/package.json
- qase-cucumberjs/package.json
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/models/attachment.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-jest/package.json
- qase-newman/package.json
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
- qase-testcafe/package.json
- qase-testcafe/src/reporter.ts
- qaseio/changelog.md
- qaseio/package.json
- qaseio/src/generated/api/attachments-api.ts
qaseio: add support uploading attachments from a string or buffer
--
Add support uploading attachments from a string or buffer. In the previous version it was possible to upload only if ReadStream was used.
---
qase-javascript-commons: Updated the process of working with attachments
--
Updated the attachment model: the content should be string or buffer.
Changed an object what describes a type of attachment and sends to qaseio.
---
qase-playwright: corrected file names for attachments
--
File names will look correct. Removed technical information from the title.
Before update: step_attach_6472eb92e81220adff0cebd05ec7beff6e160b47_ attachment.txt
After update: attachment.txt
---
release: commons 2.0.0-beta.4, playwright 2.0.0-beta.5
--
* Bump version of qase-javascript-commons to …
> qaseio: add support uploading attachments from a string or buffer

- package-lock.json
- qase-cucumberjs/package.json
- qase-cypress/package.json
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-enum.ts
- qase-javascript-commons/src/env/env-to-config.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/index.ts
- qase-javascript-commons/src/models/test-result.ts
- qase-javascript-commons/src/options/options-type.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/abstract-reporter.ts
- qase-javascript-commons/src/utils/mimeTypes.ts
- qase-jest/package.json
- qase-newman/package.json
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
- qase-testcafe/package.json
qase-javascript-commons: Update the config of reporters.
--
- Update the config of reporters. Added `captureLogs` field. If it is set to `true`, the reporter will capture logs from the test framework.
- Added `getMimeType` function to the commons package. It returns the MIME type of the file by its extension.
---
qase-playwright: add capturing logs
--
Update the reporter for attaching stdout and stderr as attachments .
---
qase-reporters: bump version of qase-javascript-commons
--
> qase-javascript-commons: Update the reporter for attaching stdout and stderr as attachments 

- package-lock.json
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
qase-playwright: Updated a message about deprecated annotations
--
Previously, we logged a message about the use of an outdated annotation immediately when running the test. Now we will log the message after all tests are completed.
> qase-playwright: Updated a message about deprecated annotations

- package-lock.json
- qase-cucumberjs/package.json
- qase-cucumberjs/src/reporter.ts
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-enum.ts
- qase-javascript-commons/src/env/env-to-config.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/models/index.ts
- qase-javascript-commons/src/models/test-result.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-jest/package.json
- qase-jest/src/reporter.ts
- qase-newman/package.json
- qase-newman/src/reporter.ts
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
- qase-testcafe/package.json
- qase-testcafe/src/reporter.ts
qase-javascript-commons: support suites
--
Add new models for support suites:
- Relation
- Suite
- SuiteData
---
qase-playwright: support suites
--
Collect the following information about suites:
- file what contains test
- test describe (if exists)
---
qase-javascript-commons: add new parameter useV2
--
Add new parameter useV2. If the parameter is true, then the testops reporter will use APIv2 methods for sending results.
---
qase-javascript-commons: add support v1
--
Add support APIv1.
---
qase-reporters: bump version of qase-javascript-commons
--
> qase-javascript-commons: add support v1

- qase-cucumberjs/package.json
- qase-cypress/package.json
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-enum.ts
- qase-javascript-commons/src/env/env-to-config.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-jest/package.json
- qase-newman/package.json
- qase-playwright/package.json
- qase-testcafe/package.json
qase-javascript-commons: change chunk to batch in the config
--
Added the following changes:
- added a new type TestOpsBatchType
- updated file and ENV configs
---
qase-javascript-commons: added log when sending results in batch upload
--
Added the following changes:
- add log about sending results in `publishResults` method
- remove this log from `publish` method
---
qase-javascript-commons: release 2.0.0-beta.8
--
Bump version and update changelog
> qase-javascript-commons: change chunk to batch in the config

- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/writer/fs-writer.ts
- qase-javascript-commons/src/writer/writer-interface.ts
qase-javascript-commons: remove old results
--
- Updated the writer interface.
- Add a method which removes old results for the file reporter
> qase-javascript-commons: remove old results

- qase-javascript-commons/src/models/index.ts
- qase-javascript-commons/src/models/step-data.ts
- qase-javascript-commons/src/models/test-step.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-playwright/src/reporter.ts
qase-javascript-commons: support different step types
--
Add support of different step types:
- StepTextData - use for ordinary steps
- StepGherkinData - use for gherkin steps
> qase-javascript-commons: support different step types

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
qase-javascript-commons: fixing a problem with duplicate test runs
--
Store the test run ID in the ENV variable `QASE_TESTOPS_RUN_ID` after creating a test run.
> qase-javascript-commons: fixing a problem with duplicate test runs

- qase-javascript-commons/changelog.md
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/abstract-reporter.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/utils/logger.ts
Improved debug logging for better testing and reporting errors.
-   Separate `logger` class for use in reporters, supporting logging to console and files.
-   Extra debug logs in both reporter modes: TestOps and Local.
>  qase-javascript-commons: improve debug logging

- qase-cypress/changelog.md
- qase-cypress/package.json
* Use qase-javascript-commons@2.0.0-beta.9 with an important bugfix.
* Add a minimal changelog.
> cypress: release 2.0.0-beta.3

- qase-cucumberjs/src/reporter.ts
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/abstract-reporter.ts
- qase-javascript-commons/src/reporters/index.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/utils/logger.ts
- qase-jest/src/reporter.ts
- qase-newman/src/reporter.ts
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
- qase-testcafe/src/factory.ts
- qase-testcafe/src/reporter.ts
qase-javascript-commons: send results strictly after creating test run
--
Fix a problem where reporter could send results before a test run in Qase was successfully created,
which resulted in a validation error and reporter switching to fallback mode.
The following changes:
- move the logger interface to the logger file
- rename ReporterInterface to InternalReporterInterface
- refactor AbstractReporter
- add a new ReporterInterface for QaseReporter
---
qase-javascript-commons: made the QaseReporter a singleton
--
The following changes:
- add `getInstance` method for creating QaseReporter
- update all reporters
---
release: qase-cypress, qase-playwright, qase-javascript-commons
--
Release the following packages:
- qase-cypress 2.0.0-beta.4
- qase-playwright 2.0.0-beta.12
- …
> qase-javascript-commons: send results strictly after creating test run

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
qase-playwright: release 2.0.0-beta.13
--
Fixed the issue with the `qase.parameters` annotation if you use not string values for parameters. Right now, the reporter will convert all parameters to strings before sending them to the Qase API.
> qase-playwright: release 2.0.0-beta.13

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- Fixed an issue when you use the `useV2` option in the reporter's configuration. This options doesn't work correctly and always uses the v1 API. 
- Fixed an issue when the step has an attachment. The attachment was not uploaded to the Qase.
> release: qase-javascript-commons 2.0.0-beta.11

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
Fixed the issue with attachments that the Playwright would create if the test failed. We have not uploaded these attachments before. This problem has now been fixed.
> release: qase-playwright 2.0.0-beta.14

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
Fixed an issue when the result has empty step action. Now the reporter will mark such steps as "Unnamed step" and will log a warning message.
> release: qase-javascript-commons 2.0.0-beta.12

- .github/workflows/npm.yml
We have come to the point of release for several packages. At the same time, we need to be able to release beta versions with new features.
Test workflow runs:
https://github.com/qase-tms/qase-javascript/actions/runs/9078010015
https://github.com/qase-tms/qase-javascript/actions/runs/9078014678
> ci: adapt workflows to publishing both release and beta versions

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/abstract-reporter.ts
release: qase-javascript-commons 2.0.1
--
Remove ANSI escape codes from the message and stack trace.
> release: qase-javascript-commons 2.0.1

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
release: qase-cypress-v2.0.1
--
The reporter would mark the test as blocked if the test was skipped in Cypress. Now, the reporter will mark the test as skipped.
> release: qase-cypress-v2.0.1

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
release: qase-cypress 2.0.2
--
Bump version
---
qase-cypress: add support suites
--
The reporter will collect suites and add them to results.
---
qase-cypress: fixed problem when completing tests
--
Cypress kills the process after the last tests. The reporter will wait for all results to be sent to Qase and will not block the  process after sending.
> release: qase-cypress 2.0.2

- qase-cucumberjs/README.md
- qase-cucumberjs/changelog.md
- qase-cucumberjs/package.json
release: qase-cucumberjs 2.0.0
--
This is the first release in the 2.x series of the Cucumber JS reporter.
> release: qase-cucumberjs 2.0.0

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-testcafe/README.md
- qase-testcafe/changelog.md
- qase-testcafe/package.json
- qase-testcafe/src/factory.ts
- qase-testcafe/src/qase.ts
- qase-testcafe/src/reporter.ts
release: qase-javascript-commons 2.0.3
--
Fixed an issue when the reporter would run tests before creating a test run.
---
qase-testcafe: add a new syntax
--
- add new syntax to annotate the following fields: `QaseID`, `QaseTitle`, `QaseFields`, `QaseParameters`
- add support suites
---
release: qase-testcafe 2.0.0-beta.2
--
Add changelog and update readme
> release: qase-javascript-commons 2.0.3 and qase-testcafe 2.0.0-beta.2

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
release: qase-javascript-commons 2.0.4
--
Fixed an issue when the reporter created a test run: `The start time does not match the format Y-m-d H:i:s.`
> release: qase-javascript-commons 2.0.4

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
release: qase-javascript-commons 2.0.5
--
Improved logging for better debugging and error reporting.
---
release: qase-playwright 2.0.1
--
Fixed an issue with using the `qase.attach()` method to add attachments with a file path.
The reporter didn't add such attachments to the test.
> release: qase-playwright 2.0.1 and qase-javascript-commons 2.0.5

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
release: qase-javascript-commons 2.0.6
--
Fixed an issue with a race condition when the reporter added test results to the test run.
> release: qase-javascript-commons 2.0.6

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/options/options-type.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qaseio/changelog.md
- qaseio/package.json
- qaseio/src/qaseio.ts
release: qaseio 2.1.1
--
Add environment API support. Now you can create, update, delete and list environments for your projects.
---
release: qase-javascript-commons 2.0.8
--
Fixed an issue with creating a test run with environment when the reporter ignored the `environment` parameter in the configuration.
> release: qaseio 2.1.1 and qase-javascript-commons 2.0.8

- qase-playwright/README.md
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
release: qase-playwright 2.0.2
--
Added new annotation for test case ignoring `qase.ignore()`. 
This annotation will mark the test as ignored in the Qase.io test run.
> release: qase-playwright 2.0.2

- qase-playwright/README.md
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
feature: add `qase.comment` annotation
--
Tests marked with it will be reported with the specified comment in the Qase.
Implement #590
---
docs: update examples
--
Add the example with steps
> release: qase-playwright 2.0.4

- qase-testcafe/README.md
- qase-testcafe/changelog.md
- qase-testcafe/package.json
release: qase-testcafe 2.0.0
--
This is the first release in the 2.x series of the TestCafe reporter. It brings a new annotation syntax with test parametrization and field values, new and more flexible configs, uploading results in parallel with running tests, and other powerful features.
> release: qase-testcafe 2.0.0

- qase-newman/README.md
- qase-newman/changelog.md
- qase-newman/package.json
release: qase-newman 2.0.0
--
This is the first release in the 2.x series of the Newman reporter. It brings new and more flexible configs, uploading results in parallel with running tests, and other powerful features.
> release: qase-newman 2.0.0

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
fix: fix an issue with sending test results duplicates
--
Fixed an issue with sending test results duplicates when we use the `qase-cypress` reporter. Now the reporter will send the test results only once.
> fix: fix an issue with sending test results duplicates

- qase-cucumberjs/src/storage.ts
- qase-cypress/src/reporter.ts
- qase-jest/src/reporter.ts
- qase-newman/src/reporter.ts
- qase-playwright/src/reporter.ts
- qase-testcafe/src/reporter.ts
feature: add a signature to the test results
--
Implement a method which constructs the signature to each test result. 
It takes the file path, the suites, the qase ids and the parameters.
> feature: add a signature to the test results

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/utils/qase-error.ts
- qaseio/changelog.md
- qaseio/package.json
- qaseio/src/qaseio.ts
feature: improve errors
--
Improve the display of error messages that occur when using the API calls. Messages will contain less unnecessary information and will be more informative for users.
[#562]
---
fix: base url for enterprise customers
--
Fix an issue with base url for enterprise customers.
---
feature: show a link if a test is failed
--
Show the link to the test result in the Qase then the test is failed.
---
release: qase-javascript-commons 2.0.11
--
Bump the version of the package and update the changelog
> feature: improve log errors and show a link of test result

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
Improve the collecting information about failed tests. 
Now, the reporter will collect the stack trace and the error message from all errors for failed tests.
> feature: improve errors

- qase-mocha/README.md
- qase-mocha/changelog.md
- qase-mocha/package.json
- qase-mocha/src/parallel.ts
- qase-mocha/src/reporter.ts
Support parallel execution of tests.
> feature: Mocha parallel execution

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/child.js
- qase-cypress/src/reporter.ts
- qase-cypress/tsconfig.build.json
Cypress doesn't finish the process after the last test. The reporter will wait for all results to be sent to Qase and will not block the process after sending.
> fix: the cypress reporter

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
fix: use a plan ID
--
If the plan ID is specified then when creating a test run it also specifies the plan ID.
---
refactor: remove a checking a test run
--
If a test run ID is specified then the reporter won't check for the existence of a test run.
---
docs: update changelog and bump version
--
> release: qase-javascript-commons 2.0.13

- package-lock.json
- qase-cypress/README.md
- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/child.js
- qase-cypress/src/hooks.ts
- qase-cypress/src/plugin.js
- qase-cypress/src/reporter.ts
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/reporters/abstract-reporter.ts
- qase-javascript-commons/src/reporters/report-reporter.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/state/state.ts
- qase-mocha/src/reporter.ts
fix: issues with sending results and completing a test run
--
- fixed an issue with the reporter completing the test run before all results are sent to Qase
- fixed an issue with the reporter not sending all results to Qase
Fixes #640 #558
---
feature: share a state between the different instances of the reporter
--
- update a `InternalReporterInterface`. Added a new methods `sendResults` and `complete` to send the results and complete the test run.
- add `StateManager` class to manage and share the state of the reporter between the different instances of the reporter.
---
Completely redesigned the reporter's workflow:
- Hooks that are executed before and after all tests will be used to create and complete test runs.
- The reporter's state will share between all instances of reporter …
> fix: issues with sending results and completing a test run in the Cypress reporter

- qase-cypress/README.md
Fixed the diff code blocks in the migration guide. See preview: https://github.com/qase-tms/qase-javascript/blob/docs/cypress-migration/qase-cypress/README.md
> docs: update code examples in Cypress migration guide

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
This allows using the standard playwright mechanism to filter the tests being run.
> fix: return the ability to add the QaseID to the test name

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
Fixed the problem when tests have the same name and different QaseIDs. They were uploaded into the Qase with an incorrect QaseID.
> fix: uploading results with the same name

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/models/error.ts
- qase-javascript-commons/src/models/index.ts
- qase-javascript-commons/src/qase.ts
- qase-javascript-commons/src/state/state.ts
Fixed an issue where the state file was not deleted. This resulted in results being uploaded into the same test run.
> fix: a state file was not deleted

- package-lock.json
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
Improved stack trace handling when an error occurs. Now, records related to the reporter are not added to the stack trace.
> feature: improve a stack trace handling

- package-lock.json
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
Reporters will send all data on the results of the autotest
> fix: send all fields

- package-lock.json
- qaseio/changelog.md
- qaseio/package.json
- qaseio/src/generated/model/result-create.ts
Add a new `param_groups` field to the `ResultCreate` model
> feature: add group parameters

- qase-mocha/changelog.md
- qase-mocha/package.json
- qase-mocha/src/reporter.ts
Fixed the issue with async tests not being reported correctly.
> fix: async tests in Mocha

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
Exclude `Before Hook` and `After Hook` from a result if they don't have children steps.
> feature: exclude empty default steps

- qase-testcafe/changelog.md
- qase-testcafe/package.json
- qase-testcafe/src/factory.ts
- qase-testcafe/src/reporter.ts
The error stack trace contains more useful debugging information: browser, code, etc.
> feature: improve error collection

- qase-wdio/changelog.md
- qase-wdio/package.json
- qase-wdio/src/reporter.ts
Fix an issue with attaching the screenshot to the test case. Now, the reporter will correctly handle the screenshots and will attach them to the test case in the Qase TMS.
[#672]
> fix: issue with attaching the screenshot

- qase-playwright/README.md
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
The `qase.id()` syntax is still supported, but the `qase()` syntax is more concise and easier to use.
> revert: the `qase.id()` syntax to `qase()`

- qase-cypress/README.md
- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/metadata.js
- qase-cypress/src/metadata/manager.ts
- qase-cypress/src/metadata/models.ts
- qase-cypress/src/mocha.ts
- qase-cypress/src/reporter.ts
- `qase.step` - add a step to the test
```ts
it('test', () => {
qase.step('Step 1', () => {
cy.visit('https://example.com');
});
});
```
> feature: the ability to add steps in tests

- package-lock.json
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
You can specify author name or email in fields.
> feature: support `author` field

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/metadata.js
- qase-cypress/src/metadata/manager.ts
- qase-cypress/src/metadata/models.ts
- qase-cypress/src/mocha.ts
- qase-cypress/src/reporter.ts
- `qase.attach` - add an attachment to test or step
```ts
it('test', () => {
qase.attach({ paths: '/path/to/file' });
qase.step('Step 1', () => {
cy.visit('https://example.com');
qase.attach({ name: 'attachment.txt', content: 'Hello, world!', contentType: 'text/plain' });
});
});
```
> feature: ability to add attachments to tests or steps

- qase-newman/README.md
Update the configuration section
> docs: update Newman readme

- qase-testcafe/changelog.md
- qase-testcafe/package.json
- qase-testcafe/src/qase.ts
- qase-testcafe/src/reporter.ts
If the test case has the `ignore` tag, the reporter will not send the result to the Qase TMS.
```ts
const q = qase.ignore().create();
test.meta({ ...q })(
'test',
async (t) => {
await t;
},
);
```
> feature: support `ignore` metadata

- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
Exclude `Worker Cleanup` step if it doesn't have children steps.
> feature: improve steps handling

- qase-jest/README.md
- qase-jest/changelog.md
- qase-jest/package.json
- qase-jest/src/global.ts
- qase-jest/src/jest.ts
- qase-jest/src/models.ts
- qase-jest/src/reporter.ts
- qase-jest/src/step.ts
- `qase.title` - set the test title
- `qase.fields` - set the test fields
- `qase.suite` - set the test suite
- `qase.comment` - set the test comment
- `qase.parameters` - set the test parameters
- `qase.groupParameters` - set the test group parameters
- `qase.ignore` - ignore the test in Qase
- `qase.attach` - attach a file to the test
- `qase.steps` - add the test steps
```ts
const { qase } = require('jest-qase-reporter/jest');
test('test', () => {
qase.title('Title');
qase.fields({ custom_field: 'value' });
qase.suite('Suite');
qase.comment('Comment');
qase.parameters({ param01: 'value' });
qase.groupParameters({ param02: 'value' });
qase.ignore();
qase.attach({ name: 'attachment.txt', content: 'Hello, world!', type: 'text/plain' });
qase.step('Step 1', () => {
expect(true).toBe(true); …
```
> feature: added the ability to specify a test metadata in tests

- package-lock.json
- qase-newman/README.md
- qase-newman/changelog.md
- qase-newman/docs/usage.md
- qase-newman/package.json
- qase-newman/src/configSchema.ts
- qase-newman/src/options.ts
- qase-newman/src/reporter.ts
```javascript
// qase.parameters: userId, user.name
pm.test("Status code is 201", function() {
pm.response.to.have.status(201);
});
```
> feature: added support parameters from data files

- package-lock.json
- qase-cypress/README.md
- qase-cypress/changelog.md
- qase-cypress/docs/usage.md
- qase-cypress/package.json
- qase-cypress/src/metadata.js
- qase-cypress/src/metadata/manager.ts
- qase-cypress/src/metadata/models.ts
- qase-cypress/src/mocha.ts
- qase-cypress/src/reporter.ts
Added the ability to specify a test metadata in tests:
- `qase.title` - set the test title
- `qase.fields` - set the test fields
- `qase.suite` - set the test suite
- `qase.comment` - set the test comment
- `qase.parameters` - set the test parameters
- `qase.groupParameters` - set the test group parameters
- `qase.ignore` - ignore the test in Qase
```ts
it('test', () => {
qase.title('Title');
qase.fields({ field: 'value' });
qase.suite('Suite');
qase.comment('Comment');
qase.parameters({ param: 'value' });
qase.groupParameters({ param: 'value' });
qase.ignore();
cy.visit('https://example.com');
});
```
---
Added the ability to add steps in tests:
- `qase.step` - add a step to the test
```ts
it('test', () => {
qase.step('Step 1', () => {
cy.visit('https://example.com');
});
});
```
--- …
> Release/qase cypress 2.2.0

- package-lock.json
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
> feature: support new version of qaseio

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
When specifying test names, QaseIDs are now excluded from the final test name. For example, `Example (Qase ID: 1)` will appear as `Example` in the test output.
> feat: remove QaseID from test names in output

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/metadata/manager.ts
When specifying the path to the Cypress config located outside the root directory, metadata was not added to the test case.
> fix: an issue with metadata

- examples/cucumberjs/package.json
- examples/cucumberjs/qase.config.json
- examples/cucumberjs/step_definitions/simple_steps.js
- package-lock.json
- qase-cucumberjs/changelog.md
- qase-cucumberjs/package.json
- qase-cucumberjs/src/storage.ts
```js
const { Given, Then } = require('cucumber');
Given('I have a step with attachment', async function () {
await this.attach('Hello, world!', 'text/plain');
});
Then('I have a step with attachment', async function () {
await this.attach('Hello, world!', 'text/plain');
});
```
> feat: support attachments in the test results

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/mocha.ts
When the `grepOmitFiltered` option is set to `true`, the reporter encounters an error.
```log
Cannot set properties of undefined (setting 'title')
```
> fix: an issue with the `@cypress/grep` plugin

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
Use the API v2 client by default. If you want to use the API v1 client, specify the `useV2` option in the config file or the environment variable `QASE_TESTOPS_USEV2` as `False`.
> feat : use the API v2 client by default

- qase-newman/changelog.md
- qase-newman/package.json
- qase-newman/src/reporter.ts
```log
Error: Error on uploading results: Bad request. Body:
{"message":"The execution.start time must be at least 1732623290. (and 1 more error)","errors":{"execution.start_time":["The execution.start time must be at least 1732623290."],"execution.end_time":["The execution.end time must be at least 1732623290."]}}
```
> fix: error when uploading results due to bad request

- examples/mocha/package.json
- examples/mocha/test/attachTests.spec.js
- examples/mocha/test/parametrizedTests.spec.js
- examples/mocha/test/simpleTests.spec.js
- examples/mocha/test/stepTests.spec.js
- package-lock.json
- qase-mocha/README.md
- qase-mocha/changelog.md
- qase-mocha/package.json
- qase-mocha/src/interceptor.ts
- qase-mocha/src/mocha.ts
- qase-mocha/src/reporter.ts
- qase-mocha/src/types.ts
This pull request includes several updates and improvements to the `qase-mocha` package, including new features, refactoring, and test updates. The most important changes include the addition of a new `qase` function, capturing console logs as test attachments, and renaming test files for better clarity.
* Added a `qase` function to allow specifying QaseID for tests.
* Implemented functionality to capture console logs and include them as attachments in tests. [[1]](diffhunk://#diff-9e21691f29dedbdadb38491a2e4666a5c2a6f3e2d0cf15a8297d1f444d2f372bR126-R181) [[2]](diffhunk://#diff-9e21691f29dedbdadb38491a2e4666a5c2a6f3e2d0cf15a8297d1f444d2f372bL173-R232)
* Renamed `examples/mocha/test/stepsTests.spec.js` to `stepTests.spec.js` for better clarity.
* Updated `mocha-qase-reporter` dependency to …
> feat: add QaseID support and console log attachments for tests

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/fileSearcher.ts
- qase-cypress/src/reporter.ts
#719 
This pull request includes several changes to the `cypress-qase-reporter` package, focusing on fixing issues with screenshot uploads, updating the package version, and refactoring the code to improve functionality and maintainability.
* Fixed an issue with screenshots not being uploaded to Qase for failed tests. (`qase-cypress/changelog.md`, `qase-cypress/src/reporter.ts`) [[1]](diffhunk://#diff-2a371c9549af06539aa3565c286f4a826afe99ffec7641cecf8cbfe5253b198bR1-R6) [[2]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1L182-R170)
* Updated the package version from `2.2.3` to `2.2.4` in `package.json`. (`qase-cypress/package.json`)
* Added a new `FileSearcher` class to handle file searching operations, replacing the old `traverseDir` function. …
> feat: add method to retrieve file attachments for failed tests

- examples/cypressCucumber/README.md
- examples/cypressCucumber/cypress-multi-reporters.js
- examples/cypressCucumber/cypress.config.js
- examples/cypressCucumber/cypress/e2e/simpleTests.feature
- examples/cypressCucumber/cypress/e2e/withQaseIDTests.feature
- examples/cypressCucumber/cypress/step_definitions/steps.js
- examples/cypressCucumber/cypress/support/commands.js
- examples/cypressCucumber/cypress/support/e2e.js
- examples/cypressCucumber/package.json
- package-lock.json
- qase-cypress/README.md
- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/cucumber.ts
- qase-cypress/src/index.cjs.ts
- qase-cypress/src/metadata.js
- qase-cypress/src/metadata/manager.ts
- qase-cypress/src/metadata/models.ts
- qase-cypress/src/reporter.ts
- qase-cypress/src/utils/tagParser.ts
- qase-javascript-commons/package.json
- qase-javascript-commons/src/utils/qase-error.ts
- tsconfig.json
This pull request introduces a new example project that demonstrates how to integrate Cypress with Cucumber and Qase Test Management. Additionally, it includes various configuration and support files for setting up and running the tests, as well as updates to the Qase Cypress reporter to support Cucumber tests. The most important changes include the addition of a README file with setup instructions, configuration files for Cypress and Cucumber, example test files, and updates to the Qase Cypress reporter package.
* [`examples/cypressCucumber/README.md`](diffhunk://#diff-9ee8e2706fbe2872563fa4bd82a272aced4317600daabffc0f121d5b7c9d37b8R1-R45): Added a new README file with detailed setup instructions for integrating Cypress with Cucumber and Qase Test Management.
* …
> feat: support Cucumber in Cypress reporter

- examples/cypressCucumber/package.json
- package-lock.json
- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/fileSearcher.ts
- qase-cypress/src/reporter.ts
- Added recursive folder search by a specified name.
- Screenshots for failed tests are now correctly attached, even if the tests are located in subdirectories.
This pull request includes several changes to the `qase-cypress` package, focusing on fixing an issue with screenshot attachments for failed tests and updating the package version. The most important changes are the addition of a new method to search for folders by name and modifying the file search logic to correctly handle subdirectories.
Fixes and improvements:
* [`qase-cypress/changelog.md`](diffhunk://#diff-2a371c9549af06539aa3565c286f4a826afe99ffec7641cecf8cbfe5253b198bR1-R6): Added a new entry for version `2.2.6` detailing the fix for attaching screenshots of failed tests located in subdirectories.
* …
> fix: issue with attaching screenshots for failed tests in subdirectories

- package-lock.json
- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/fileSearcher.ts
This pull request includes several updates to the `cypress-qase-reporter` package, addressing a bug fix and a version bump. The most important changes are as follows:
Bug Fix:
* [`qase-cypress/src/fileSearcher.ts`](diffhunk://#diff-d3ad025eefb90638d963b844ca1a29c72461288a5d20e658aca6b904e239b49cR54-R57): Added a check to ensure the directory exists before attempting to read its contents, preventing errors when the screenshot folder does not exist.
Version Update:
* [`qase-cypress/package.json`](diffhunk://#diff-f50f25410e8641426bca1d154b56935d9f8ae5fcbce8c26b153cefcdbc5b7509L3-R3): Updated the package version from `2.2.6` to `2.2.7`.
* [`qase-cypress/changelog.md`](diffhunk://#diff-2a371c9549af06539aa3565c286f4a826afe99ffec7641cecf8cbfe5253b198bR1-R6): Added a new entry for version …
> fix: an issue where the reporter got error if screenshot folder was not exist

- qase-cypress/changelog.md
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
This pull request includes several updates to the `cypress-qase-reporter` package, focusing on fixing an issue with attachments on Windows and updating the package version. The most important changes are summarized below:
Bug fix:
* [`qase-cypress/src/reporter.ts`](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1L268-R268): Fixed an issue where attachments were not properly linked to failed tests on Windows by updating the path separator to use `path.sep` instead of a hardcoded forward slash. [[1]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1L268-R268) [[2]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1L296-R296)
Version update:
* …
> fix: fixed attachment issue for failed tests on Windows

- qase-jest/changelog.md
- qase-jest/package.json
- qase-jest/src/reporter.ts
This pull request introduces several changes to the `jest-qase-reporter` package, focusing on improving the processing of test names by automatically removing Qase IDs when uploading results. The key changes include updating the version, modifying the test title processing, and adding a new private method.
Improvements to test name processing:
* [`qase-jest/src/reporter.ts`](diffhunk://#diff-2cc13d88ad00969f429268e945fb6e3868da9b625af6cef0fc7f939d921617a9L334-R334): Modified the `title` field to use the new `removeQaseIdsFromTitle` method to strip Qase IDs from test titles.
* [`qase-jest/src/reporter.ts`](diffhunk://#diff-2cc13d88ad00969f429268e945fb6e3868da9b625af6cef0fc7f939d921617a9R355-R367): Added a new private method `removeQaseIdsFromTitle` to handle the removal of Qase IDs from …
> feat: added removeQaseIdsFromTitle method to remove IDs from test names

- package-lock.json
- qase-javascript-commons/package.json
This pull request includes updates to the `qase-javascript-commons` package, including a version bump and the removal of an unused dependency.
Version update:
* [`qase-javascript-commons/package.json`](diffhunk://#diff-ceddde62b79232841e644c4ff2b16bedf8bfa08c98c3193e2e034bd8875d7f9cL3-R3): Updated the package version from `2.2.8` to `2.2.9`.
Dependency management:
* [`qase-javascript-commons/package.json`](diffhunk://#diff-ceddde62b79232841e644c4ff2b16bedf8bfa08c98c3193e2e034bd8875d7f9cL29): Removed the `child-process-ext` dependency as it is no longer needed.
> chore: remove unused dependency child-process-ext

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/state/state.ts
This pull request includes updates to the `qase-javascript-commons` package, focusing on resolving an issue with parallel execution of multiple reporters and updating the package version. The most important changes include modifying the state synchronization file path and updating the version in `package.json`.
* [`qase-javascript-commons/src/state/state.ts`](diffhunk://#diff-1dead262c2b8dc521c83b4b0421bb8717594e75ef5a1e57aec61081c865fc2d9L12-R12): Changed the `statePath` in `StateManager` to use `process.cwd()` instead of `__dirname` to ensure each reporter uses its own dedicated file for state synchronization.
* [`qase-javascript-commons/package.json`](diffhunk://#diff-ceddde62b79232841e644c4ff2b16bedf8bfa08c98c3193e2e034bd8875d7f9cL3-R3): Updated the package version from `2.2.9` to …
> fix: resolve parallel reporter execution issue by using separate sync files

- package-lock.json
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/reporters/testops-reporter.ts
This pull request introduces a new mutex to ensure correct result submission when running tests in multiple threads, preventing potential duplication. The changes include updates to the package version, dependencies, and modifications to the `TestOpsReporter` class to integrate the mutex.
* [`qase-javascript-commons/src/reporters/testops-reporter.ts`](diffhunk://#diff-9b393f0c08ec0ce57dfc974a338ccb75a4255b298ecb250e667334a757f288feR36): Added `Mutex` import and integrated it into the `TestOpsReporter` class to ensure thread safety during result submission and publishing. [[1]](diffhunk://#diff-9b393f0c08ec0ce57dfc974a338ccb75a4255b298ecb250e667334a757f288feR36) [[2]](diffhunk://#diff-9b393f0c08ec0ce57dfc974a338ccb75a4255b298ecb250e667334a757f288feR168-R169) …
> fix: add mutex to ensure correct result submission in multi-threaded tests

- qase-cucumberjs/src/storage.ts
It is now possible to use multiple test case IDs separated by commas, for example: @QaseID=2,3,4
> Update to support multiple Qase IDs in a single autotest.

- qase-cucumberjs/changelog.md
- qase-cucumberjs/package.json
- qase-cucumberjs/src/storage.ts
This pull request includes updates to the `qase-cucumberjs` package to enable support for multiple IDs in the `QaseID` tag. The most important changes include updating the regular expression to handle multiple IDs, modifying the storage class to process multiple IDs, and updating the package version.
Enhancements to `QaseID` tag support:
* [`qase-cucumberjs/src/storage.ts`](diffhunk://#diff-b70a3b5b898c3a7bd91062af6785c9f3a77927767b96fcbd4b2a93d3fe4ee0a1L28-R28): Updated the `newQaseIdRegExp` regular expression to support multiple IDs.
* [`qase-cucumberjs/src/storage.ts`](diffhunk://#diff-b70a3b5b898c3a7bd91062af6785c9f3a77927767b96fcbd4b2a93d3fe4ee0a1L339-R339): Modified the `Storage` class to split and map multiple IDs into the `metadata.ids` array.
Documentation and versioning:
* …
> feat: support for multiple IDs in the `QaseID` tag

- package-lock.json
- qase-cucumberjs/package.json
- qase-cypress/package.json
- qase-cypress/src/reporter.ts
- qase-javascript-commons/package.json
- qase-javascript-commons/src/models/step-data.ts
- qase-javascript-commons/src/models/test-step.ts
- qase-javascript-commons/src/reporters/testops-reporter.ts
- qase-javascript-commons/src/steps/step.ts
- qase-jest/package.json
- qase-jest/src/step.ts
- qase-mocha/package.json
- qase-mocha/src/reporter.ts
- qase-playwright/changelog.md
- qase-playwright/docs/usage.md
- qase-playwright/package.json
- qase-playwright/src/playwright.ts
- qase-playwright/src/reporter.ts
- qase-testcafe/package.json
- qase-wdio/package.json
- qase-wdio/src/reporter.ts
- qase-wdio/src/step.ts
This pull request includes multiple changes across various packages to introduce new functionality and update dependencies. The most significant changes involve adding a new `data` field to step data structures and updating the `qase-javascript-commons` dependency version across all packages.
* Added the ability to specify `data` for each step in `qase-cypress`, `qase-javascript-commons`, `qase-jest`, `qase-mocha`, `qase-playwright`, and `qase-wdio`. This includes updates to the respective `Step` classes and interfaces. [[1]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1R365) [[2]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1R392) [[3]](diffhunk://#diff-a9d14bef553a558532fda3402f52cb9e68e7641503ef19a485323aa421870536R …
> feat: add support for specifying expected result and data for steps

- package-lock.json
- package.json
- qaseio/babel.config.js
- qaseio/jest.config.js
- qaseio/package.json
- qaseio/src/qaseio.ts
This pull request introduces several updates and improvements to the project, including dependency updates, configuration changes, and type modifications. Below are the most important changes:
* Updated the `axios` dependency to version `^1.8.2` in `qaseio/package.json`.
* Added `babel-jest` to the `devDependencies` in `package.json`.
* Added Babel configuration in `qaseio/babel.config.js` with the preset `@babel/preset-env`.
* Updated `jest.config.js` to include `babel-jest` for transforming JavaScript files and added `transformIgnorePatterns` to exclude `node_modules` except for `axios`.
* Changed the `QaseApiOptionsType` from a `type` to an `interface` in `qaseio/src/qaseio.ts`.
#756
> Dependabot/npm and yarn/axios 1.8.2

- package-lock.json
- qase-mocha/changelog.md
- qase-wdio/changelog.md
- qase-wdio/package.json
- qase-wdio/src/storage.ts
This pull request includes several updates and improvements across multiple packages, mainly focusing on the `qase-wdio` and `qase-mocha` packages. The most significant changes include version updates, changelog additions, and a bug fix in the `Storage` class.
**Changelog Updates:**
* [`qase-mocha/changelog.md`](diffhunk://#diff-b408629d8cfd1cdc4f952b2339cdf7d72a9bbb1b5939db2edbdda37ea2158fc8L5-R5): Updated the changelog to reflect the major release of the Mocha reporter package.
* [`qase-wdio/changelog.md`](diffhunk://#diff-8343aa0a0d3a3e6cbac3f8e9ecc22786105c91f1ee77e254e264576ed8467a99R1-R12): Added entries for versions 1.0.0 and 1.0.1, including a fix for handling parent test suites.
**Version Updates:**
* [`qase-wdio/package.json`](diffhunk://#diff-65edb3d91c6eb943e1c8807c2d36ab59b49c …
> fix: correct handling of parent test suites

- qase-mocha/changelog.md
- qase-mocha/package.json
- qase-mocha/src/reporter.ts
This pull request includes enhancements to the `qase-mocha` package, specifically improving the handling of test and step start and end times for more accurate reporting. The most important changes include updating the version number, adding new properties for timing, and modifying the test handling methods to record and report accurate timings.
Enhancements to test and step timing:
* [`qase-mocha/src/reporter.ts`](diffhunk://#diff-9e21691f29dedbdadb38491a2e4666a5c2a6f3e2d0cf15a8297d1f444d2f372bR62): Added `testBeginTime` property to record the start time of tests and updated `onStartTest` and `onEndTest` methods to calculate and store accurate start, end, and duration times for tests. [[1]](diffhunk://#diff-9e21691f29dedbdadb38491a2e4666a5c2a6f3e2d0cf15a8297d1f444d2f372bR62) …
> feat: improve start/end time handling for tests and steps

- qase-wdio/changelog.md
- qase-wdio/package.json
- qase-wdio/src/reporter.ts
This pull request includes updates to the `qase-wdio` package, specifically addressing a bug fix, version bump, and code improvements. The most important changes are summarized below:
* Resolved an issue where a custom suite set via `qase.suite` was not included in the test results. (`qase-wdio/changelog.md`, `qase-wdio/src/reporter.ts`) [[1]](diffhunk://#diff-8343aa0a0d3a3e6cbac3f8e9ecc22786105c91f1ee77e254e264576ed8467a99R1-R6) [[2]](diffhunk://#diff-b59909cf64d6c06c8fe5356db40408673e67035e467a10b36634973f15eadcdaR278) [[3]](diffhunk://#diff-b59909cf64d6c06c8fe5356db40408673e67035e467a10b36634973f15eadcdaR292-R293)
* Updated the package version from `1.0.1` to `1.0.2` in `package.json`. (`qase-wdio/package.json`)
> fix: ensure custom suite from `qase.suite` is correctly applied

- qaseio/changelog.md
- qaseio/package.json
- qaseio/src/qaseio.ts
This pull request includes updates to the `qaseio` package to introduce a new search functionality in the API client. The most important changes include adding a new field to the search endpoint and updating the API client to support this new functionality.
* [`qaseio/changelog.md`](diffhunk://#diff-f50ddec8a96cd317ca79728e3615a8e507b79106917af61aadcda974be1c83ebR1-R7): Added a new field in the search endpoint of the public API contract and extended API client functionality to accommodate the updated contract.
* [`qaseio/package.json`](diffhunk://#diff-f68cebf949e240a3c55ba44c6caf0430f09fae964cd1a1272087844c9d00da45L3-R3): Updated the version from `2.4.2` to `2.4.3` to reflect the new changes.
* `qaseio/src/qaseio.ts`: 
* Added `SearchApi` to the imports.
* Included `search` in the …
> feat: update API client contract with search endpoint field

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/utils/hostData.ts
This pull request includes several updates to the `qase-javascript-commons` package to resolve an issue and improve error handling. The most important changes are listed below:
* Updated the package version to `2.2.18` in `package.json`.
* Added a new entry in the changelog for version `2.2.18`, detailing the resolved issue with retrieving installed package versions when some dependencies were missing.
* Enhanced the `getPackageVersion` function in `hostData.ts` to handle errors more gracefully by adding a try-catch block around the `execCommand` call. This ensures that if the command fails, the function returns `null` instead of throwing an error.
#774
> fix: handle package version retrieval errors in npm list

- qase-newman/changelog.md
- qase-newman/package.json
- qase-newman/src/reporter.ts
This pull request addresses a bug fix in the `qase-newman` package related to parent suite hierarchy handling in test results. It includes changes to the changelog, version bump, and a functional fix in the reporter logic.
* **Parent Suite Hierarchy Handling**:
- Fixed the logic in `getParentTitles` within `qase-newman/src/reporter.ts` to ensure the titles array is updated correctly when traversing parent items. This resolves the issue of improperly displayed suite structures in test results.
* **Changelog Update**:
- Added an entry in `qase-newman/changelog.md` for version `2.1.1`, describing the fix for the parent suite hierarchy issue.
* **Version Bump**:
- Updated the package version in `qase-newman/package.json` from `2.1.0` to `2.1.1` to reflect the bug fix.
> fix: correct handling of parent suites in test results

- package-lock.json
- qase-api-client/package.json
- qase-api-v2-client/package.json
- qaseio/package.json
- qaseio/src/qaseio.ts
axios-retry 3.* depends on a vulnerable version of @babel/runtime
4.* no longer depends on @babel/runtime
See https://github.com/advisories/GHSA-968p-4wvh-cqc8
> chore: bump axios-retry to 4.5.0

- qase-playwright/changelog.md
- qase-playwright/docs/usage.md
- qase-playwright/package.json
- qase-playwright/src/reporter.ts
This pull request introduces several updates to the `playwright-qase-reporter` package, including a new feature for specifying test case suites via annotations, documentation improvements, and internal code changes for better functionality and maintainability.
* Added support for defining test case suites using the `annotation` property in test definitions. This allows users to specify suites directly in their test code for better organization. (`qase-playwright/src/reporter.ts`, [[1]](diffhunk://#diff-3f15218cd3a03d6ac76683c4437c053029f848df708978f79ff7c29c8818df1eL343-R347) [[2]](diffhunk://#diff-3f15218cd3a03d6ac76683c4437c053029f848df708978f79ff7c29c8818df1eR521-R536)
* Updated `qase-playwright/docs/usage.md` to improve readability and consistency. This includes reformatting text, …
> feat: support setting suite via annotations

- qase-api-client/package.json
- qase-api-v2-client/package.json
- qase-javascript-commons/package.json
- qase-javascript-commons/src/client/clientV1.ts
- qase-javascript-commons/src/client/dateUtils.ts
- qase-playwright/package.json
- qaseio/package.json
This pull request includes version updates across multiple packages and enhancements to the `qase-javascript-commons` codebase. The version updates ensure compatibility between dependencies, while the code improvements focus on logging clarity and time handling.
* Updated the version of `qase-api-client` to `1.0.1` in its `package.json` file.
* Updated the version of `qase-api-v2-client` to `1.0.1` in its `package.json` file.
* Updated the version of `qase-javascript-commons` to `2.3.1` in its `package.json` file and updated its dependencies to use `qase-api-client@~1.0.1` and `qase-api-v2-client@~1.0.1`. [[1]](diffhunk://#diff-ceddde62b79232841e644c4ff2b16bedf8bfa08c98c3193e2e034bd8875d7f9cL3-R3) [[2]](diffhunk://#diff-ceddde62b79232841e644c4ff2b16bedf8bfa08c98c3193e2e034bd8875d7f9cL35-R3 …
> fix: ensure run start time is before first test execution

- qase-api-client/package.json
- qase-api-client/src/model/test-step-result-create.ts
- qase-api-client/src/model/test-step-result.ts
- qase-api-v2-client/docs/ResultStepStatus.md
- qase-api-v2-client/package.json
- qase-api-v2-client/src/model/result-step-status.ts
- Updated package versions for qase-api-client and qase-api-v2-client to 1.0.2
- Added 'in_progress' status to TestStepResultCreateStatusEnum and ResultStepStatus enums
- Updated documentation to reflect the new 'in_progress' status
> feat: bump package versions and add new test step status

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/client/clientV1.ts
- Updated package version to 2.3.2
- Added entry in changelog for fixing attachment content type issue
> chore: bump version to 2.3.2 and update changelog

- package-lock.json
- qase-playwright/README.md
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/configSchema.ts
- qase-playwright/src/options.ts
- qase-playwright/src/reporter.ts
- Updated changelog to reflect new version 2.1.3
- Added support for specifying the browser name as a parameter in the Playwright configuration
- Introduced new properties in the configuration schema for browser parameter options
- Updated README to include new configuration options for browser parameter
> feat:  add browser parameter support

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/env/env-to-config.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- Updated package version to 2.3.4
- Fixed tag parsing from `QASE_TESTOPS_RUN_TAGS` environment variable to accept comma-separated strings
- Updated changelog to reflect the new version and changes
> fix: tag parsing from `QASE_TESTOPS_RUN_TAGS`

- qase-playwright/docs/usage.md
- Expanded the usage guide in docs/usage.md to include a new section on selective execution of tests using the `grep` property.
- Provided examples for configuration-based filtering and command line filtering.
- Included instructions for using `qasectl` to filter test plans based on Qase IDs.
- Enhanced the documentation to improve usability and clarity for users integrating Qase with Playwright.
> docs: add selective execution tests section to usage guide

- qase-cypress/test/configSchema.test.ts
- qase-cypress/test/fileSearcher.test.ts
- qase-cypress/test/reporter.test.ts
- qase-cypress/test/tagParser.test.ts
- qase-wdio/jest.config.js
- qase-wdio/test/hooks.test.ts
- qase-wdio/test/storage.test.ts
- qase-wdio/test/utils.test.ts
This pull request introduces comprehensive test coverage across multiple components and modules in the `qase-cypress` and `qase-wdio` packages. The changes include the addition of unit tests for schema validation, file searching, reporting, tag parsing, and hook execution, as well as the setup of a Jest configuration for the `qase-wdio` package.
* **Schema Validation:**
- Added tests in `qase-cypress/test/configSchema.test.ts` to validate the structure and properties of the `configSchema`, ensuring it is correctly defined, nullable, and includes expected nested properties such as `framework` and `cypress`.
* **File Searching:**
- Implemented tests in `qase-cypress/test/fileSearcher.test.ts` for the `FileSearcher` utility, covering scenarios such as finding files before a specific time, …
> test: add unit tests

- qase-playwright/README.md
- qase-playwright/changelog.md
- qase-playwright/package.json
- qase-playwright/src/configSchema.ts
- qase-playwright/src/options.ts
- qase-playwright/src/reporter.ts
- Updated package version to 2.1.4.
- Added support for marking tests as flaky if they passed after retries.
- Updated documentation to include new `framework.markAsFlaky` option in README and changelog.
> feat: update to version 2.1.4 with support for flaky tests

- qase-javascript-commons/README.md
- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/client/clientV1.ts
- qase-javascript-commons/src/config/config-validation-schema.ts
- qase-javascript-commons/src/env/env-enum.ts
- qase-javascript-commons/src/env/env-to-config.ts
- qase-javascript-commons/src/env/env-type.ts
- qase-javascript-commons/src/env/env-validation-schema.ts
- qase-javascript-commons/src/models/config/TestOpsOptionsType.ts
- qase-javascript-commons/src/models/configuration.ts
- qase-javascript-commons/src/models/index.ts
- qase-javascript-commons/test/config/config-validation-schema.test.ts
- qase-javascript-commons/test/env/env-to-config.test.ts
- qase-javascript-commons/test/env/env-validation-schema.test.ts
This pull request introduces support for managing configurations in Qase TestOps, including creating and associating configuration groups and values with test runs. The changes span documentation updates, new API integrations, configuration schema extensions, and validation tests. Below is a breakdown of the most important changes:
* Updated `qase-javascript-commons/README.md` to document new configuration options (`testops.configurations.values` and `testops.configurations.createIfNotExists`) and provide an example configuration. [[1]](diffhunk://#diff-a86b9b2bf39ba11a85fcbbda1d3ef20cf0156c82eee3cd7acff6192547c7e3a7R61-R62) [[2]](diffhunk://#diff-a86b9b2bf39ba11a85fcbbda1d3ef20cf0156c82eee3cd7acff6192547c7e3a7R97-R109)
* Added `ConfigurationsApi` and related models …
> feat: add configuration support

- package-lock.json
- qase-mocha/changelog.md
- qase-mocha/package.json
- qase-mocha/src/parallel.ts
- qase-mocha/src/reporter.ts
- Bumped version from 1.1.3 to 1.1.4.
- Updated Mocha dependency to version 11.0.0.
- Adjusted qase-javascript-commons dependency to version 2.4.4.
- Fixed compatibility issue with parallel mode in Mocha 11.0.0.
- Updated changelog to reflect the new version and changes.
#831
> fix: compatibility issue with parallel mode in Mocha 11.0.0

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/utils/test-status-utils.ts
- qase-javascript-commons/test/utils/test-status-utils.test.ts
- Updated version from 2.4.6 to 2.4.7 in package.json.
- Added a changelog entry for bug fixes, addressing the issue of test results with unknown statuses being incorrectly marked as `skipped`.
- Implemented case-insensitive status matching in test-status-utils for improved compatibility.
- Added tests to verify case-insensitive status handling and default behavior for unknown statuses.
> chore: bump version to 2.4.7 and update changelog

- qase-javascript-commons/changelog.md
- qase-javascript-commons/package.json
- qase-javascript-commons/src/utils/test-status-utils.ts
- qase-javascript-commons/test/utils/test-status-utils.test.ts
- Updated version from 2.4.7 to 2.4.8 in package.json.
- Added a changelog entry for improved error handling of timeout errors.
- Enhanced test-status-utils to treat timeout errors with expect as assertion errors.
- Added new tests to verify the behavior of timeout errors in various scenarios.
> chore: bump version to 2.4.8 and update changelog

- qase-cucumberjs/changelog.md
- qase-cucumberjs/package.json
- qase-cucumberjs/src/storage.ts
- Updated version from 2.1.5 to 2.1.6 in package.json.
- Added changelog entry for bug fix addressing incorrect mapping of cucumber-specific statuses.
- Adjusted status mapping logic in storage.ts to ensure proper handling of `AMBIGUOUS` status.
> chore: bump version to 2.1.6 and update changelog
