qase-tms/qase-javascript

qaseio/src/models/runs.ts, qaseio/test/services/runs.test.ts
Set is_autotest as optional field inside RunCreate class
=> Set is_autotest as optional field inside RunCreate class

qaseio/package.json
Updated version before publishing to npm
=> [qaseio] Updated version

qase-testcafe/examples/.qaserc, qase-testcafe/examples/package-lock.json, qase-testcafe/examples/package.json, qase-testcafe/examples/test.js
Added a simple test-case example for TestCafe.
=> Created TestCafe example

qaseio/package.json
Bumped version to v2.0.0-alpha.4
=> [qaseio] Bumped version

qaseio/package-lock.json, qaseio/package.json
https://github.com/axios/axios/commit/51f3ccb08ea944c79fd008d82a17466549a1dfa3
=> [qaseio] Bumped axios version to fix trouble with follow-redirects

qase-jest/package-lock.json, qase-jest/package.json
Fixed follow-redirects and shelljs vulnerability
=> [qase-jest] Bumped qaseio version

qase-cypress/src/mocha.ts
https://github.com/qase-tms/qase-javascript/issues/116
=> Fix for cypress grep

qase-cypress/package.json, qase-cypress/src/index.ts
Fix timeout message and bump version
=> Increase cypress timeout

qase-playwright/package-lock.json, qase-playwright/package.json, qase-playwright/src/index.ts
Fixed eslint, bumped version, resolved vulnerabilities
=> [qase-playwright] Fixed eslint, bumped version, resolved vulnerabilities

qaseio/package-lock.json, qaseio/package.json
=> build(deps): audit fix in qaseio

qase-newman/README.md
noticed a missing letter, then added it.
=> Fix minor spelling error

package-lock.json, qase-playwright/changelog.md, qase-playwright/package.json
qase-playwright: fix problem with dependencies
--
Fix the error:
` Error [ERR_REQUIRE_ESM]: require() of ES Module /__w/app/app/tests/e2e/node_modules/playwright-qase-reporter/node_modules/chalk/source/index.js from /__w/app/app/tests/e2e/node_modules/playwright-qase-reporter/dist/reporter.js not supported.`
=> qase-playwright: fix problem with dependencies

qase-playwright/changelog.md, qase-playwright/package.json, qase-playwright/src/playwright.ts
qase-playwright: using the `qase` annotation in a chain
--
Added self-return to each annotation.
=> qase-playwright: using the `qase` annotation in a chain

qase-cypress/README.md
Update a few lines in the readme.
=> Cypress release 2.0.0-beta.2

qase-cypress/README.md
Add a short instruction on migrating from v1 to v2
=> qase-cypress: how to migrate from v1

.gitignore, README.md
* Point to the stable v1 and new v2 versions
* To be updated when v2 betas come to release
* To be cherry-picked into the master branch
Readme preview: https://github.com/qase-tms/qase-javascript/blob/readme-introduction/README.md
=> docs: make a navigation table with all reporters

qase-jest/changelog.md, qase-jest/package.json
* This release brings support for multiple changes made in the Qase API client and the qase-javascript-commons library.
Resolves #576
=> release: jest-qase-reporter@2.0.0-beta.2

qase-jest/package.json
release: qase-jest 2.0.1
--
Bump the package version to 2.0.1
=> release: qase-jest 2.0.1

qase-cucumberjs/src/reporter.ts
release: qase-cucumberjs 2.0.0-beta.2
--
Added support steps.
=> release: qase-cucumberjs 2.0.0-beta.2

qase-cucumberjs/README.md
docs: update qase-cucumberjs readme
--
Update qase-cucumberjs readme:
- add section how to update from v1
- update examples
- update execution command
- update configuration section
=> docs: update qase-cucumberjs readme

package-lock.json, package.json, qaseio/changelog.md, qaseio/package.json
release: qaseio 2.1.2
--
Update `axios` dependency to `^0.28.0` for fixes vulnerabilities CVE-2023-45857
=> release: qaseio 2.1.2

qase-newman/changelog.md, qase-newman/package.json, qase-newman/src/reporter.ts
release: qase-newman 2.0.0-beta.2
--
Added support suites for the Newman reporter
=> release: qase-newman 2.0.0-beta.2

qase-playwright/changelog.md, qase-playwright/package.json, qase-playwright/src/reporter.ts
Improve the log message about the old and new test annotation syntax.
Resolve #628
=> release: qase-playwright-reporter@2.0.5

qase-javascript-commons/changelog.md, qase-javascript-commons/package.json, qase-javascript-commons/src/reporters/testops-reporter.ts, qaseio/changelog.md, qaseio/package.json, qaseio/src/generated/api/environments-api.ts, qaseio/src/generated/model/run-create.ts, qaseio/src/generated/model/run.ts
Added search for environments and creation of test runs with the addition of an environment slug
=> feature: update the api client

qase-playwright/package.json, qase-playwright/src/reporter.ts
Fix the issue where QaseID was not assigned to the test.
=> fix: ability to add the QaseID to the test name

qase-cypress/package.json
Fix package build. Executables were not included in the package.
=> fix: package build

qase-cypress/changelog.md, qase-cypress/package.json, qase-cypress/src/child.js
Fixed an issue with the reporter completing the test run after each file with tests.
=> fix: completing the test run

qase-cypress/changelog.md, qase-cypress/package.json, qase-javascript-commons/changelog.md, qase-javascript-commons/package.json, qase-playwright/changelog.md, qase-playwright/package.json, qase-playwright/src/playwright.ts, qase-playwright/src/reporter.ts
Minor release of the Cypress reporter
=> Bump versions

package-lock.json, qase-cucumberjs/package.json, qase-cucumberjs/src/storage.ts, qase-cypress/package.json, qase-cypress/src/reporter.ts, qase-javascript-commons/package.json, qase-javascript-commons/src/models/test-result.ts, qase-javascript-commons/src/reporters/testops-reporter.ts, qase-jest/package.json, qase-jest/src/reporter.ts, qase-mocha/changelog.md, qase-mocha/package.json, qase-mocha/src/reporter.ts, qase-mocha/src/types.ts, qase-newman/package.json, qase-newman/src/reporter.ts, qase-playwright/changelog.md, qase-playwright/package.json, qase-playwright/src/playwright.ts, qase-playwright/src/reporter.ts, qase-testcafe/changelog.md, qase-testcafe/package.json, qase-testcafe/src/qase.ts, qase-testcafe/src/reporter.ts, qase-wdio/changelog.md, qase-wdio/package.json, qase-wdio/src/events.ts, qase-wdio/src/reporter.ts, qase-wdio/src/wdio.ts
Add support the group parameters in the JS reporters
=> feature: add group parameters

qase-playwright/README.md
fixed typos for debug option description default* ... environment*
=> Update README.md - fix typos

qaseio/changelog.md, qaseio/package.json, qaseio/src/generated/model/author.ts
Added a new `author_id` and `entity_id` fields to the `Author` model.
=> feature: update `author` model

qase-playwright/changelog.md, qase-playwright/package.json, qase-playwright/src/reporter.ts
Improve excluding default steps, like `Worker Cleanup`, `Before …
=> fix: improve excluding default steps

qase-javascript-commons/changelog.md, qase-javascript-commons/package.json, qase-javascript-commons/src/state/state.ts
Fixed an issue when the reporter saves the state file in the wrong directory.
=> fix: an issue with reporter state

qase-javascript-commons/changelog.md, qase-javascript-commons/package.json, qase-javascript-commons/src/reporters/testops-reporter.ts
This pull request includes updates to the `qase-javascript-commons` package, focusing on enhancing error handling and updating the package version. The most important changes include improving error messages for 403 status code responses and updating the version number.
Enhancements to error handling:
* [`qase-javascript-commons/src/reporters/testops-reporter.ts`](diffhunk://#diff-9b393f0c08ec0ce57dfc974a338ccb75a4255b298ecb250e667334a757f288feR813-R817): Added a specific error message for 403 status code responses to provide clearer feedback.
Version update:
* [`qase-javascript-commons/package.json`](diffhunk://#diff-ceddde62b79232841e644c4ff2b16bedf8bfa08c98c3193e2e034bd8875d7f9cL3-R3): Updated the package version from 2.2.12 to 2.2.13.
Documentation update:
* …
=> feat: improve error messaging for 403 status code responses

qase-cypress/changelog.md, qase-cypress/package.json, qase-cypress/src/reporter.ts, qase-javascript-commons/changelog.md, qase-javascript-commons/package.json, qase-javascript-commons/src/reporters/testops-reporter.ts
This pull request includes updates to both the `qase-cypress` and `qase-javascript-commons` packages. The changes enhance test reporting accuracy and improve error handling and diagnostics.
* Updated the version to `2.2.10` and added a changelog entry describing the enhanced handling of start and end times for tests and steps. [[1]](diffhunk://#diff-2a371c9549af06539aa3565c286f4a826afe99ffec7641cecf8cbfe5253b198bR1-R6) [[2]](diffhunk://#diff-f50f25410e8641426bca1d154b56935d9f8ae5fcbce8c26b153cefcdbc5b7509L3-R3)
* Modified the `CypressQaseReporter` class to calculate and store the test duration and start/end times more accurately. [[1]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b4765edeb6df860afd59eea2e1R150-R152) [[2]](diffhunk://#diff-efec16f566a83cc38003751fae999771a55cb5b47 …
=> feat: improve start/end time handling for tests and steps

package-lock.json, qase-javascript-commons/changelog.md, qase-javascript-commons/package.json, qase-javascript-commons/src/models/host-data.ts, qase-javascript-commons/src/qase.ts, qase-javascript-commons/src/reporters/report-reporter.ts, qase-javascript-commons/src/utils/hostData.ts, qase-wdio/package.json, qase-wdio/src/hooks.ts, qase-wdio/src/reporter.ts
This pull request includes several changes to the `qase-javascript-commons` and `qase-wdio` packages, focusing on improving the logging of host system details and refactoring code for better maintainability. The most important changes include updating the version numbers, refactoring the `HostData` type, and integrating a new utility function for gathering host information.
* Updated `qase-javascript-commons` to version 2.2.17 (`qase-javascript-commons/package.json`)
* Updated `wdio-qase-reporter` to version 1.0.3 (`qase-wdio/package.json`)
* Added logging of host system details and installed packages in logs for better debugging and traceability (`qase-javascript-commons/changelog.md`)
* Changed `HostData` type to an interface and updated its structure to include more detailed system …
=> feat: add logging of host information and installed packages

examples/jest/README.md, examples/jest/jest.config.js, examples/jest/package.json, examples/jest/test/attach.test.js, examples/jest/test/comment.test.js, examples/jest/test/fields.test.js, examples/jest/test/id.test.js, examples/jest/test/ignore.test.js, examples/jest/test/markdownContent.js, examples/jest/test/params.test.js, examples/jest/test/steps.test.js, examples/jest/test/suite.test.js, examples/jest/test/title.test.js, qase-jest/README.md
This pull request includes several updates and improvements to the Jest example project. The changes focus on enhancing the documentation, updating dependencies, and refining the test configuration and scripts.
* Added a new `README.md` file with detailed setup instructions for the Jest example project, including prerequisites, setup steps, and additional resources.
* Updated the `jest.config.js` file to enable the `uploadAttachments` option in the `testops` configuration.
* Updated the `package.json` file to use the latest version of `jest-qase-reporter` and modified the test script to run Jest in band mode.
* Added imports for `describe`, `test`, and `expect` from `@jest/globals` in multiple test files to ensure compatibility with the latest Jest version. …
=> docs: update documentation and test examples

qase-cucumberjs/src/storage.ts, qase-cucumberjs/test/reporter.test.ts, qase-cucumberjs/test/storage.test.ts, qase-javascript-commons/test/config/config-loader.test.ts, qase-javascript-commons/test/formatter/json-formatter.test.ts, qase-javascript-commons/test/formatter/jsonp-formatter.test.ts, qase-javascript-commons/test/models/error.test.ts, qase-javascript-commons/test/options/composeOptions.test.ts, qase-javascript-commons/test/reporters/report-reporter.test.ts, qase-javascript-commons/test/reporters/testops-reporter.test.ts, qase-javascript-commons/test/state/state.test.ts, qase-javascript-commons/test/utils/disabled-exception.test.ts, qase-javascript-commons/test/utils/get-package-version.test.ts, qase-javascript-commons/test/utils/is-axios-error.test.ts, qase-javascript-commons/test/utils/mimeTypes.test.ts, qase-javascript-commons/test/utils/signature.test.ts, qase-javascript-commons/test/utils/validate-json.test.ts, qase-javascript-commons/test/writer/fs-writer.test.ts, qase-jest/test/global.test.ts, qase-jest/test/jest.test.ts, qase-jest/test/models.test.ts, qase-jest/test/reporter.test.ts, qase-newman/src/reporter.ts, qase-newman/test/reporter.test.ts, qase-playwright/test/playwright.test.ts, qase-playwright/test/reporter.test.ts, qase-testcafe/test/reporter.test.ts
This pull request introduces several changes aimed at improving regular expression handling, enhancing test coverage, and adding new test cases for configuration loaders and formatters. The most significant changes include simplifying regular expressions, mocking dependencies for unit tests, and creating comprehensive test suites for various components.
=> test: add unit tests

examples/cypress/cypress.config.js, examples/cypress/package.json, package-lock.json, qase-cypress/README.md, qase-cypress/package.json, qase-cypress/src/configSchema.ts, qase-cypress/src/hooks.ts, qase-cypress/src/options.ts, qase-cypress/src/reporter.ts, qase-javascript-commons/package.json, qase-javascript-commons/src/client/clientV1.ts, qase-javascript-commons/src/client/clientV2.ts, qase-javascript-commons/src/client/interface.ts, qase-javascript-commons/src/models/test-result.ts, qase-javascript-commons/src/qase.ts, qase-javascript-commons/src/reporters/abstract-reporter.ts, qase-javascript-commons/src/reporters/report-reporter.ts, qase-javascript-commons/src/reporters/testops-reporter.ts, qase-javascript-commons/test/reporters/testops-reporter.test.ts
This pull request introduces significant updates to the Qase Cypress Reporter, focusing on adding video upload functionality, improving attachment handling, and upgrading dependencies. Key changes include enabling video uploads with configurable delays, enhancing the attachment upload process, and updating the package versions to beta releases for new features.
* Added `uploadDelay` configuration in `cypress.config.js` to introduce a delay before uploading video files. Videos are now uploaded after test execution if the `video` option is enabled. (`[[1]](diffhunk://#diff-d05993df795d619e99b7b68b7c8a996afa1d16462dfe50155e58163bd60c8b60R28-R42)`, `[[2]](diffhunk://#diff-c88a4419ad2ec51323f197982cec543bbcc47fc0162f4db7230732aecc02d000R30-R35)`, …
=> feat: implement attachment upload functionality

qase-cypress/changelog.md, qase-cypress/package.json, qase-cypress/src/fileSearcher.ts, qase-cypress/src/hooks.ts, qase-cypress/test/fileSearcher.test.ts
- Fixed an issue where video attachments were not uploaded for tests located in subdirectories.
- Updated changelog and package version to 3.0.2 in package.json.
- Enhanced file searching functionality to support video files in subdirectories.
- Added tests for video file searching functionality.
#819
=> feat: release cypress-qase-reporter@3.0.2
